### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by ainesskk** [Mutabona/LibSevSUBackend#2]
Добрый вечер, заметила в базе данных 2 пользователя с логином "yyyyyy", и с паролями, отличающимися на 1 символ, это авторская задумка?

**Comment by Mutabona** [comment]
Добрый вечер, Ксения! Мне очень жаль, что вы столкнулись с такой проблемой :(, однако спешу вас заверить, что такой проблемы нет, скорее всего вы использовали для одного из них русские символы, а эту возможность я в последних обновлениях убрал.
